-- Active: 1698494014678@@127.0.0.1@3306@hospital
SELECT PATIENT.PID,PATIENT.`DoctorId`,PATIENT.`Fname`,PATIENT.`Lname`,PATIENT.`Contact1`,PATIENT.`Contact2`,
PATIENT.`Age`,PATIENT.`Gender`,PATIENT.`Patient_type`,DOCTOR.`DoctorId`,DOCTOR.`PID`,DOCTOR.`LabId`,DOCTOR.`Name`,DOCTOR.`Lname`
FROM PATIENT
INNER JOIN DOCTOR ON PATIENT.`DoctorId`=DOCTOR.`DoctorId`;