-- Active: 1698494014678@@127.0.0.1@3306@hospital
DELIMITER $$

CREATE PROCEDURE INSERT_DATA(
    IN p_billid INT, 
    IN p_PID INT, 
    IN p_NAME_OF_THE_PATIENT VARCHAR(25), 
    IN p_AMOUNT FLOAT, 
    IN p_DATE DATE
)
BEGIN
    INSERT INTO BILL (BILLID, PID, NAME_OF_THE_PATIENT, AMOUNT, DATE)
    VALUES (p_billid, p_PID, p_NAME_OF_THE_PATIENT, p_AMOUNT, p_DATE);
END;

DELIMITER ;

DELIMITER$$

CREATE PROCEDURE AMOUNT_BILL(IN p1 INT)
BEGIN
    SELECT BILLID, PID, NAME_OF_THE_PATIENT, DATE, SUM(AMOUNT) AS TOTALAMOUNT
    FROM BILL
    WHERE PID = p1;
END;


DELIMITER $$